In [4]:
import polars as pl

In [5]:
root = "/Users/mohamedali/trading_project/earnings_ibapi"

In [17]:


lf = pl.scan_pyarrow_dataset(f"{root}/data/contract_descriptions")

AttributeError: 'str' object has no attribute 'schema'

In [18]:
from pathlib import Path
import polars as pl

base = Path(root) / "data/contract_descriptions"
files = sorted(p for p in base.rglob("*.parquet") if p.is_file())
if not files:
    raise FileNotFoundError(f"No .parquet files under {base}")

In [19]:
base

PosixPath('/Users/mohamedali/trading_project/earnings_ibapi/data/contract_descriptions')

In [21]:
src = f"{root}/data/contract_descriptions/*/*/*.parquet"
lf = pl.scan_parquet(src)

In [22]:
lf.head(5).collect()

shape: (5, 6)
┌───────────┬────────┬──────────┬──────────┬──────────────────┬─────────────────────────┐
│ conid     ┆ symbol ┆ sec_type ┆ currency ┆ primary_exchange ┆ derivative_sec_types    │
│ ---       ┆ ---    ┆ ---      ┆ ---      ┆ ---              ┆ ---                     │
│ i64       ┆ str    ┆ str      ┆ str      ┆ str              ┆ list[str]               │
╞═══════════╪════════╪══════════╪══════════╪══════════════════╪═════════════════════════╡
│ -1        ┆        ┆ BOND     ┆          ┆                  ┆ []                      │
│ 8314      ┆ IBM    ┆ STK      ┆ USD      ┆ NYSE             ┆ ["CFD", "OPT", … "BAG"] │
│ 1411277   ┆ IBM    ┆ STK      ┆ EUR      ┆ IBIS             ┆ ["IOPT"]                │
│ 38709473  ┆ IBM    ┆ STK      ┆ MXN      ┆ MEXI             ┆ []                      │
│ 530091934 ┆ IBM    ┆ STK      ┆ CAD      ┆ AEQLIT           ┆ []                      │
└───────────┴────────┴──────────┴──────────┴──────────────────┴─────────────────────────┘

In [24]:
lf.filter(pl.col("derivative_sec_types").list.contains("OPT")).collect()

shape: (1, 6)
┌───────┬────────┬──────────┬──────────┬──────────────────┬─────────────────────────┐
│ conid ┆ symbol ┆ sec_type ┆ currency ┆ primary_exchange ┆ derivative_sec_types    │
│ ---   ┆ ---    ┆ ---      ┆ ---      ┆ ---              ┆ ---                     │
│ i64   ┆ str    ┆ str      ┆ str      ┆ str              ┆ list[str]               │
╞═══════╪════════╪══════════╪══════════╪══════════════════╪═════════════════════════╡
│ 8314  ┆ IBM    ┆ STK      ┆ USD      ┆ NYSE             ┆ ["CFD", "OPT", … "BAG"] │
└───────┴────────┴──────────┴──────────┴──────────────────┴─────────────────────────┘